Imports:

In [81]:
import numpy as np

Input data:

In [82]:
A = np.array([
    [1, -1, 0],
    [0, 1, 0],
    [0, 0, 1],
])
x = np.array(
    [1, 0, 1]
    )
i = 2

Find reverse of A:

In [83]:
IA = np.linalg.inv(A)

print(IA)

[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Replace column:

In [84]:
RA = A.copy()
RA[:,i] = x[::]

print(RA)

[[ 1 -1  1]
 [ 0  1  0]
 [ 0  0  1]]


Check matrix invertibility:

In [85]:
l = IA.dot(x)
print(l)

if (l[i] == 0):
    print("Matrix is non invertible.")
    exit(0)

[1. 0. 1.]


Change i'th element in l vector:

In [86]:
ln = l.copy()
ln[i] = -1

print(ln)

[ 1.  0. -1.]


Calculate lˆ= −1/li * l

In [87]:
ls = (-1/l[i]) * ln
print(ls)

[-1. -0.  1.]


Identity matrix with changed column:

In [88]:
Q = np.eye(len(A))
Q[:,i] = ls

print(Q)

[[ 1.  0. -1.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


Reverse matrix:

In [89]:
res = np.matmul(Q, IA)

print(res)

[[ 1.  1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
